name: Java CI with Maven on Green_Phase_Complete Branch

on:
  push:
    branches:
      - Green_Phase_Complete
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Change directory
      run: cd finalProject
    - name: Build with Maven
      run: |
        cd finalProject
        mvn -B package --file pom.xml
    - name: Run specific tests
      run: |
        cd finalProject
        mvn test