name: Java CI with Maven on kunal_springboot Branch

on:
  push:
    branches:
      - kunal_springboot
    # Optional: paths filter if you want to run only when specific files change
    # paths:
    #   - 'finalProject/src/test/java/com/ontariotechu/sofe3980U/**'
  pull_request:
    branches:
      - main
    # Optional: paths filter for PRs as well
    # paths:
    #   - 'finalProject/src/test/java/com/ontariotechu/sofe3980U/**'

jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run specific tests
      run: mvn test
